services:
  app:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    environment:
      SERVER_NAME: "api.uanggue.my.id"
      DOCUMENT_ROOT: "/var/www/html/public"
    command: ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - storage_data:/var/www/html/storage
      - ./logs/laravel:/var/www/html/storage/logs
      - ./logs/caddy:/data/caddy/logs
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"] # Cek ke endpoint /up Laravel atau root /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - uangku-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - uangku-network

  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
        - 'redis_data:/data'
    networks:
        - uangku-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  uangku-network:
    driver: bridge

volumes:
  storage_data:
  db_data:
  caddy_data:
  caddy_config:
  redis_data: