services:
  app:
    # Nama image nanti kita buat dinamis dari GitHub Actions
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG:-latest}
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - uangku-network

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"  # Membuka gerbang dunia luar (80) ke Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro # Agar Nginx bisa baca file statis (CSS/JS)
    networks:
      - uangku-network
    depends_on:
      - app

  mysql:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uangku-network

networks:
  uangku-network:
    driver: bridge

volumes:
  storage_data:
  db_data: