name: Build and Push to Registry

on:
  push:
    branches: [ main ] # Robot ini bakal kerja pas lo merge ke main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production # Ini kunci biar dia bisa baca secrets lo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Nanti kita akan tambahkan Login ke DigitalOcean di sini
      - name: Build and Test Image
        run: |
          docker build -t uanggue-prod:latest .
          docker run --rm uanggue-prod:latest php artisan --version